### PR TITLE
fix: allow nesting form groups

### LINKED ISSUE #110: Allow nested groups
**Describe the bug**
It seems that currently it is only possible to have `FormGroups` at the root level of a form.

**To Reproduce**
```html
<pre>{{values}}</pre>
<InputText name="name" label="Your Name" />
<FormGroup name="account" label="Account">
      <InputText name="name" label="Account Name" />
      <FormGroup name="company" label="Company">
          <InputText name="name" label="Company Name" />
          <FormGroup name="name" label="Address">
               <InputText name="name" label="Street Name" />
          </FormGroup>
      </FormGroup>
</FormGroup>

```

The groups are not tested

**Expected behavior**
I'd like the `FormGroup` component to be namespaced according to the hierarchy

### PR DESCRIPTION
**Pull request by genu**
Fixes #110 

This PR allows creating nested form groups like so:

```html
<FormGroup name="account" label="Account">
      <InputText name="name" label="Account Name" />
      <FormGroup name="company" label="Company">
        <InputText name="name" label="Company Name" />
        <FormGroup name="address" label="Address">
          <InputText name="name" label="Street Name" />
        </FormGroup>
      </FormGroup>
    </FormGroup>
```

### CODE REVIEW

File: packages/core/src/useFormGroup/useFormGroup.ts [hunk 1]
```diff
@@ -66,7 +66,17 @@ export function useFormGroup<TInput extends FormObject = FormObject, TOutput ext
...
   const props = normalizeProps(_props, ['schema']);
-  const getPath = () => toValue(props.name);
+  const pathPrefixer = usePathPrefixer();
+
+  const getPath = () => {
+    const path = toValue(_props.name);
+
+    const prefixPath = pathPrefixer ? pathPrefixer.prefixPath(path) : path;
+
+    if (!prefixPath) return path;
```
Comment (logaretm) [inline packages/core/src/useFormGroup/useFormGroup.ts:76]: Let's add a block here, I should probably add an eslint rule for it.
```suggestion
    if (!prefixPath) {
      return path;
    }
```

**Review by logaretm — CHANGES_REQUESTED** [review]
Looks good to me, but lets add tests and I left a very minor comment.

**Review by logaretm — APPROVED** [review]
